# -*- coding: utf-8 -*-
"""Exception handling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wGiqoPjoKA3OUaMGQh_f6XXfvZ1yRtzX
"""

try:
    print('Try block')
    x=int(input('Enter the first number: '))
    y=int(input('Enter second number: '))
    z=x/y
except ZeroDivisionError:
    print("Can't divide by zero!!")
else:
    print("HI I AM ELSE BLOCK")
    print("Division = ", z)
finally:
    print("Finally block  executed!.")
print ("Out of all blocks!." )